Server:
  RunMode: "debug"
  HttpPort: "8088"
  ReadTimeout: 5
  WriteTimeout: 5
Database:
  DBType: "mysql"
  UserName: "root"
  Password: "11111111"
  Host: 127.0.0.1:3306
  DBName: "bookManage"
  TablePrefix: book_
  Charset: "utf8"
  ParseTime: "True"
  MaxIdleConns: 10
  MaxOpenConns: 30
Log:
  Level: "Info"
  Filename: "logs/test.log"
  MaxSize: 20
  MaxAge: 10
  MaxBackups: 7